# L

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/ektarr/counter-strike-pro-matches/players.csv
/kaggle/input/datasets/ektarr/counter-strike-pro-matches/teams.csv
/kaggle/input/datasets/ektarr/counter-strike-pro-matches/tournaments.csv
/kaggle/input/datasets/ektarr/counter-strike-pro-matches/cs2_tier1_games.csv
/kaggle/input/datasets/ektarr/counter-strike-pro-matches/cs2_tier3_games.csv
/kaggle/input/datasets/ektarr/counter-strike-pro-matches/cs2_all_tiers_games.csv
/kaggle/input/datasets/ektarr/counter-strike-pro-matches/cs2_tier2_games.csv

In [2]:
PATH_ALL_TIERS_GAMES = '/kaggle/input/datasets/ektarr/counter-strike-pro-matches/cs2_all_tiers_games.csv'
PATH_TIER_1_GAMES = '/kaggle/input/datasets/ektarr/counter-strike-pro-matches/cs2_tier1_games.csv'
PATH_TIER_2_GAMES = '/kaggle/input/datasets/ektarr/counter-strike-pro-matches/cs2_tier2_games.csv'
PATH_TIER_3_GAMES = '/kaggle/input/datasets/ektarr/counter-strike-pro-matches/cs2_tier3_games.csv'

PLAYERS = '/kaggle/input/datasets/ektarr/counter-strike-pro-matches/players.csv'
TEAMS = '/kaggle/input/datasets/ektarr/counter-strike-pro-matches/teams.csv'
TOURNAMENTS = '/kaggle/input/datasets/ektarr/counter-strike-pro-matches/tournaments.csv'

In [3]:
df_all = pd.read_csv(PATH_ALL_TIERS_GAMES)
df_tier1 = pd.read_csv(PATH_TIER_1_GAMES)
df_tier2 = pd.read_csv(PATH_TIER_2_GAMES)
df_tier3 = pd.read_csv(PATH_TIER_3_GAMES)

df_players = pd.read_csv(PLAYERS)
df_teams = pd.read_csv(TEAMS)
df_tournaments = pd.read_csv(TOURNAMENTS)

In [4]:
print(df_all.shape)
print(df_tier1.shape)
print(df_tier2.shape)
print(df_tier3.shape)

(19031, 99)
(10274, 99)
(7743, 99)
(1014, 99)

In [5]:
df_all.head(10)

,Unnamed: 0,match_id,game_id,tournament,team1_id,team1,team2_id,team2,score1_match,score2_match,...,team2_player4_assists,team2_player4_adr,team2_player4_kast,team2_player4_kddiff,team2_player5_kills,team2_player5_deaths,team2_player5_assists,team2_player5_adr,team2_player5_kast,team2_player5_kddiff
0,0,7299109,153292.0,PGL Astana 2026. Closed European Qualifier,289672,magic,289673,K27,3.0,2.0,...,4.0,98.6,77.3,12.0,14.0,18.0,8.0,64.5,68.2,-4.0
1,1,7299109,153294.0,PGL Astana 2026. Closed European Qualifier,289672,magic,289673,K27,3.0,2.0,...,2.0,67.2,72.7,6.0,13.0,16.0,8.0,76.8,72.7,-3.0
2,2,7299109,-153292.0,PGL Astana 2026. Closed European Qualifier,289672,magic,289673,K27,3.0,2.0,...,6.0,82.9,75.0,18.0,27.0,34.0,16.0,70.7,70.5,-7.0
3,3,7299050,153284.0,PGL Astana 2026. Closed European Qualifier,289670,K27,289671,100 Thieves,2.0,1.0,...,1.0,69.5,73.9,7.0,9.0,11.0,4.0,57.0,73.9,-2.0
4,4,7299050,153289.0,PGL Astana 2026. Closed European Qualifier,289670,K27,289671,100 Thieves,2.0,1.0,...,3.0,63.6,78.9,-1.0,10.0,13.0,4.0,66.2,68.4,-3.0
5,5,7299050,153290.0,PGL Astana 2026. Closed European Qualifier,289670,K27,289671,100 Thieves,2.0,1.0,...,3.0,77.5,83.3,-1.0,18.0,11.0,1.0,67.7,66.7,7.0
6,6,7299050,-153284.0,PGL Astana 2026. Closed European Qualifier,289670,K27,289671,100 Thieves,2.0,1.0,...,7.0,70.2,78.7,5.0,37.0,35.0,9.0,63.6,69.7,2.0
7,7,7299028,153278.0,PGL Astana 2026. Closed European Qualifier,289668,ACROBATS,289669,100 Thieves,1.0,2.0,...,3.0,78.0,63.2,-1.0,13.0,12.0,2.0,68.5,57.9,1.0
8,8,7299028,153280.0,PGL Astana 2026. Closed European Qualifier,289668,ACROBATS,289669,100 Thieves,1.0,2.0,...,9.0,92.5,71.4,3.0,16.0,10.0,3.0,60.5,66.7,6.0
9,9,7299028,-153278.0,PGL Astana 2026. Closed European Qualifier,289668,ACROBATS,289669,100 Thieves,1.0,2.0,...,12.0,85.3,67.3,2.0,29.0,22.0,5.0,64.5,62.3,7.0

In [6]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19031 entries, 0 to 19030
Data columns (total 99 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             19031 non-null  int64
 1   match_id               19031 non-null  int64
 2   game_id                14542 non-null  float64
 3   tournament             19031 non-null  object
 4   team1_id               19031 non-null  int64
 5   team1                  19030 non-null  object
 6   team2_id               19031 non-null  int64
 7   team2                  19030 non-null  object
 8   score1_match           19030 non-null  float64
 9   score2_match           19030 non-null  float64
 10  is_total               19031 non-null  bool
 11  bestOf                 18896 non-null  float64
 12  score1_game            12368 non-null  float64
 13  score2_game            12368 non-null  float64
 14  map_id                 12321 non-null  float64
 15  map_name               12321 non-null  object
 16  datetime               19031 non-null  object
 17  team1_win              19031 non-null  int64
 18  games_played           19030 non-null  float64
 19  team1_player1_id       18281 non-null  float64
 20  team1_player2_id       18073 non-null  float64
 21  team1_player3_id       18096 non-null  float64
 22  team1_player4_id       18071 non-null  float64
 23  team1_player5_id       17643 non-null  float64
 24  team2_player1_id       17788 non-null  float64
 25  team2_player2_id       17612 non-null  float64
 26  team2_player3_id       17603 non-null  float64
 27  team2_player4_id       17526 non-null  float64
 28  team2_player5_id       17248 non-null  float64
 29  team1_player1          14192 non-null  object
 30  team1_player2          14005 non-null  object
 31  team1_player3          14073 non-null  object
 32  team1_player4          14083 non-null  object
 33  team1_player5          13762 non-null  object
 34  team2_player1          13933 non-null  object
 35  team2_player2          13867 non-null  object
 36  team2_player3          13845 non-null  object
 37  team2_player4          13781 non-null  object
 38  team2_player5          13523 non-null  object
 39  team1_player1_kills    14192 non-null  float64
 40  team1_player1_deaths   14192 non-null  float64
 41  team1_player1_assists  14192 non-null  float64
 42  team1_player1_adr      14192 non-null  float64
 43  team1_player1_kast     14192 non-null  float64
 44  team1_player1_kddiff   14192 non-null  float64
 45  team1_player2_kills    14005 non-null  float64
 46  team1_player2_deaths   14005 non-null  float64
 47  team1_player2_assists  14005 non-null  float64
 48  team1_player2_adr      14005 non-null  float64
 49  team1_player2_kast     14005 non-null  float64
 50  team1_player2_kddiff   14005 non-null  float64
 51  team1_player3_kills    14073 non-null  float64
 52  team1_player3_deaths   14073 non-null  float64
 53  team1_player3_assists  14073 non-null  float64
 54  team1_player3_adr      14073 non-null  float64
 55  team1_player3_kast     14073 non-null  float64
 56  team1_player3_kddiff   14073 non-null  float64
 57  team1_player4_kills    14083 non-null  float64
 58  team1_player4_deaths   14083 non-null  float64
 59  team1_player4_assists  14083 non-null  float64
 60  team1_player4_adr      14083 non-null  float64
 61  team1_player4_kast     14083 non-null  float64
 62  team1_player4_kddiff   14083 non-null  float64
 63  team1_player5_kills    13762 non-null  float64
 64  team1_player5_deaths   13762 non-null  float64
 65  team1_player5_assists  13762 non-null  float64
 66  team1_player5_adr      13762 non-null  float64
 67  team1_player5_kast     13762 non-null  float64
 68  team1_player5_kddiff   13762 non-null  float64
 69  team2_player1_kills    13933 non-null  float64
 70  team2_player1_deaths   13933 non-null  float64
 71  team2_player1_assists  13933 non-null  float64
 72  team2_player1_adr      13933 non-null  float64
 73  team2_player1_kast     13933 non-null  float64
 74  team2_player1_kddiff   13933 non-null  float64
 75  team2_player2_kills    13867 non-null  float64
 76  team2_player2_deaths   13867 non-null  float64
 77  team2_player2_assists  13867 non-null  float64
 78  team2_player2_adr      13867 non-null  float64
 79  team2_player2_kast     13867 non-null  float64
 80  team2_player2_kddiff   13867 non-null  float64
 81  team2_player3_kills    13845 non-null  float64
 82  team2_player3_deaths   13845 non-null  float64
 83  team2_player3_assists  13845 non-null  float64
 84  team2_player3_adr      13845 non-null  float64
 85  team2_player3_kast     13845 non-null  float64
 86  team2_player3_kddiff   13845 non-null  float64
 87  team2_player4_kills    13781 non-null  float64
 88  team2_player4_deaths   13781 non-null  float64
 89  team2_player4_assists  13781 non-null  float64
 90  team2_player4_adr      13781 non-null  float64
 91  team2_player4_kast     13781 non-null  float64
 92  team2_player4_kddiff   13781 non-null  float64
 93  team2_player5_kills    13523 non-null  float64
 94  team2_player5_deaths   13523 non-null  float64
 95  team2_player5_assists  13523 non-null  float64
 96  team2_player5_adr      13523 non-null  float64
 97  team2_player5_kast     13523 non-null  float64
 98  team2_player5_kddiff   13523 non-null  float64
dtypes: bool(1), float64(78), int64(5), object(15)
memory usage: 14.2+ MB

In [7]:
match_id = 7299109

df_match_id = df_all[df_all['match_id'] == match_id]
df_match_id

,Unnamed: 0,match_id,game_id,tournament,team1_id,team1,team2_id,team2,score1_match,score2_match,...,team2_player4_assists,team2_player4_adr,team2_player4_kast,team2_player4_kddiff,team2_player5_kills,team2_player5_deaths,team2_player5_assists,team2_player5_adr,team2_player5_kast,team2_player5_kddiff
0,0,7299109,153292.0,PGL Astana 2026. Closed European Qualifier,289672,magic,289673,K27,3.0,2.0,...,4.0,98.6,77.3,12.0,14.0,18.0,8.0,64.5,68.2,-4.0
1,1,7299109,153294.0,PGL Astana 2026. Closed European Qualifier,289672,magic,289673,K27,3.0,2.0,...,2.0,67.2,72.7,6.0,13.0,16.0,8.0,76.8,72.7,-3.0
2,2,7299109,-153292.0,PGL Astana 2026. Closed European Qualifier,289672,magic,289673,K27,3.0,2.0,...,6.0,82.9,75.0,18.0,27.0,34.0,16.0,70.7,70.5,-7.0

In [8]:
df_match_id_subset = df_match_id[['is_total', 'bestOf', 'map_name', 'score1_match', 'score2_match', 'score1_game', 'score2_game']]
df_match_id_subset

,is_total,bestOf,map_name,score1_match,score2_match,score1_game,score2_game
0,False,5.0,Ancient,3.0,2.0,9.0,13.0
1,False,5.0,Mirage,3.0,2.0,9.0,13.0
2,True,5.0,Anubis,3.0,2.0,13.0,6.0

In [9]:
df_match_group = df_all.groupby('match_id')['is_total'].sum()
df_match_group.value_counts()

is_total
1    9199
2       2
Name: count, dtype: int64

In [10]:
df_match_group

match_id
487653      1
487656      1
557551      1
557623      1
557625      1
           ..
10091157    1
10091160    1
10091161    1
10091171    1
10091172    1
Name: is_total, Length: 9201, dtype: int64

In [11]:
match_id = df_match_group[df_match_group == 2]
match_id

match_id
794633    2
794634    2
Name: is_total, dtype: int64

In [12]:
match_id = [794633, 794634]
df_filtr_match = df_all[df_all['match_id'].isin(match_id)]

df_filtr_match_subset = df_filtr_match[['match_id' ,'is_total', 'bestOf', 'map_name', 'score1_match', 'score2_match', 'score1_game', 'score2_game']]
df_filtr_match_subset

,match_id,is_total,bestOf,map_name,score1_match,score2_match,score1_game,score2_game
9409,794634,False,3.0,Ancient,0.0,2.0,2.0,13.0
9410,794634,False,3.0,Inferno,0.0,2.0,8.0,13.0
9411,794634,True,3.0,Mirage,0.0,2.0,0.0,0.0
9412,794633,False,3.0,Mirage,0.0,2.0,9.0,13.0
9413,794633,False,3.0,Overpass,0.0,2.0,8.0,13.0
9414,794633,True,3.0,Ancient,0.0,2.0,0.0,0.0
9417,794633,False,3.0,Mirage,0.0,2.0,9.0,13.0
9418,794633,False,3.0,Overpass,0.0,2.0,8.0,13.0
9419,794633,True,3.0,Ancient,0.0,2.0,0.0,0.0
9420,794634,False,3.0,Ancient,0.0,2.0,2.0,13.0
9421,794634,False,3.0,Inferno,0.0,2.0,8.0,13.0
9422,794634,True,3.0,Mirage,0.0,2.0,0.0,0.0

In [13]:
df_all.duplicated().sum()

np.int64(0)